name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  
  publish:
    needs: [build]
    runs-on: windows-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Package
      shell: bash
      run: |
        subversion=`date +%Y%m%d`
        echo $subversion
        dotnet pack src/ExcelDataReader.FieldMaps -o /publish/ -c Release -p:PackageVersion=3.6.0-ci-$subversion-${{github.run_id}}
    - name: push nuget
      run:
        dotnet nuget push /publish/*.nupkg -k ${{secrets.nuget_apikey}} -s https://api.nuget.org/v3/index.json
